"""Review model change to SelfReview

Revision ID: db189331cab0
Revises: 
Create Date: 2023-10-11 14:44:38.101946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db189331cab0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood_rating', sa.Integer(), nullable=False),
    sa.Column('today_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_self_review_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('review')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_card_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_card_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deck_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], name='fk_review_deck_id_deck'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_review_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('self_review')
    # ### end Alembic commands ###
